name: Claude Code Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  claude-assist:
    # 只在评论中包含 @claude 时触发
    if: |
      github.event.issue.pull_request != null ||
      (contains(github.event.comment.body, '@claude') || 
       contains(github.event.comment.body, '@Claude'))
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Claude Code Action
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # 启用所有工具
          tools: "Read,Edit,Write,Bash,Grep"
          # 设置工作目录
          working_dir: "."
          # 模型选择
          model: "claude-3-5-sonnet-20241022"